language: scala
script:
- sbt clean update compile test doc
after_script:
- ./update_scaladoc.sh
jdk:
- openjdk7
- oraclejdk8
env:
  global:
    secure: awWHs3Tw0MpBetD5FaL+qj6VYLsgywJiX8S0xN/hPHc7noS+Ja+KNMONm1RyiJwsk0CLcdnLhrVlbPMGpbBMN3KacqyhVT7i/herO0vh1tQpBo4rE22vYCJwWC5x2o9YQ0kNREHmxsI12jVmFi1FoWOC5kvcmWbJIS3b9hmfjZo=
